
name: "[DEV] Build and Publish iOS"
on:
  push:
    branches:
      - circleci-project-setup
jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Set up fastlane
        run: gem install fastlane

      - name: Set up CocoaPods
        run: pod install --project-directory=ios

      - name: Build iOS
        run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath ${{ github.workspace }}/ios/Runner.xcarchive archive

      - name: Export Archive
        run: xcodebuild -exportArchive -archivePath ${{ github.workspace }}/ios/Runner.xcarchive -exportPath ${{ github.workspace }}/ios/Runner -exportOptionsPlist ios/Runner/ExportOptions.plist
        
      - name: Create AuthKey.p8 file
        run: echo "${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}" > AuthKey.p8

      - name: Upload to TestFlight
        run: fastlane pilot upload --api_key_path ./path/to/AuthKey.p8 --api_key_id ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }} --api_issuer ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }} --ipa ${{ github.workspace }}/ios/Runner.ipa